
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
import javax.sound.sampled.*;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shah
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    static int sound = 2;
    static InputStream inputStream;
    static AudioStream audioStream;
    ImageIcon imageOn = new ImageIcon(getClass().getResource("/soundOn.png"));
    ImageIcon imageOff = new ImageIcon(getClass().getResource("/soundOff.png"));
    
    public MainMenu() {
        initComponents();      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ShipInfo = new javax.swing.JButton();
        ShipGraphic = new javax.swing.JButton();
        ShipSudoku = new javax.swing.JButton();
        ShipShuffle = new javax.swing.JButton();
        buttonOnSound = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Trading Ship Puzzle");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 10, 155, 22);

        ShipInfo.setText("Ship Information");
        ShipInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShipInfoActionPerformed(evt);
            }
        });
        jPanel1.add(ShipInfo);
        ShipInfo.setBounds(60, 100, 160, 23);

        ShipGraphic.setText("See The Ship");
        ShipGraphic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShipGraphicActionPerformed(evt);
            }
        });
        jPanel1.add(ShipGraphic);
        ShipGraphic.setBounds(60, 160, 160, 23);

        ShipSudoku.setText("Shidoku");
        jPanel1.add(ShipSudoku);
        ShipSudoku.setBounds(60, 290, 160, 23);

        ShipShuffle.setText("Shuffle The Ship");
        jPanel1.add(ShipShuffle);
        ShipShuffle.setBounds(60, 230, 160, 23);

        buttonOnSound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soundOn.png"))); // NOI18N
        buttonOnSound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOnSoundActionPerformed(evt);
            }
        });
        jPanel1.add(buttonOnSound);
        buttonOnSound.setBounds(240, 410, 40, 40);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Credit.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(0, 410, 40, 41);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Off.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 410, 40, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ocean.gif"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-10, 0, 290, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void musicPlay()
    {
        
        try
        {               
            if(sound == 2)
            {
                inputStream = new FileInputStream("GameSong.wav");
                audioStream = new AudioStream(inputStream);
            }            
            if(sound == 1)
            {
                AudioPlayer.player.stop(audioStream);  
                sound = 2;
                return;
            }    
            if(sound == 0 || sound == 2)
            {
                AudioPlayer.player.start(audioStream);
                sound = 1;
            }
                
            
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }    
    
    private void ShipInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShipInfoActionPerformed
        new Qna().setVisible(true); 
        dispose(); 
    }//GEN-LAST:event_ShipInfoActionPerformed

    private void ShipGraphicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShipGraphicActionPerformed
        new GraphicalShip().setVisible(true);
    }//GEN-LAST:event_ShipGraphicActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       new Credit().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void buttonOnSoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOnSoundActionPerformed
        if(sound == 1)
        {
            musicPlay();
            buttonOnSound.setIcon(imageOn);             
            return;
        }
        if(sound == 0 || sound == 2)
        {
            musicPlay();            
            buttonOnSound.setIcon(imageOff);                      
        }        
    }//GEN-LAST:event_buttonOnSoundActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ShipGraphic;
    private javax.swing.JButton ShipInfo;
    private javax.swing.JButton ShipShuffle;
    private javax.swing.JButton ShipSudoku;
    private javax.swing.JButton buttonOnSound;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
