/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shah & Ikhwan
 */
public class Position extends javax.swing.JFrame {

    /**
     * Creates new form Position
     */
    public Position() {
        initComponents();
        new GraphicalShip().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        NewPosition1 = new javax.swing.JLabel();
        NewPosition2 = new javax.swing.JLabel();
        NewPosition0 = new javax.swing.JLabel();
        NewPosition3 = new javax.swing.JLabel();
        NewPosition4 = new javax.swing.JLabel();
        Ocean2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Position0 = new javax.swing.JLabel();
        Position1 = new javax.swing.JLabel();
        Position2 = new javax.swing.JLabel();
        Position3 = new javax.swing.JLabel();
        Position4 = new javax.swing.JLabel();
        Ocean1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        NewPosition1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(NewPosition1);
        NewPosition1.setBounds(160, 130, 150, 110);

        NewPosition2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(NewPosition2);
        NewPosition2.setBounds(310, 240, 150, 110);

        NewPosition0.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(NewPosition0);
        NewPosition0.setBounds(10, 240, 150, 110);

        NewPosition3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(NewPosition3);
        NewPosition3.setBounds(460, 130, 150, 110);

        NewPosition4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(NewPosition4);
        NewPosition4.setBounds(610, 240, 150, 110);

        Ocean2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OceanPosition.gif"))); // NOI18N
        jPanel3.add(Ocean2);
        Ocean2.setBounds(10, 80, 760, 290);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("New Position");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(310, 10, 130, 30);

        jLabel5.setText("Place the ship into new position");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(280, 50, 160, 14);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        Position0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrenchShip.png"))); // NOI18N
        jPanel2.add(Position0);
        Position0.setBounds(30, 240, 150, 110);

        Position1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GreekShip.png"))); // NOI18N
        jPanel2.add(Position1);
        Position1.setBounds(180, 160, 150, 110);

        Position2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BrazilianShip.png"))); // NOI18N
        jPanel2.add(Position2);
        Position2.setBounds(320, 240, 150, 110);

        Position3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnglishShip.png"))); // NOI18N
        jPanel2.add(Position3);
        Position3.setBounds(460, 160, 150, 110);

        Position4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SpanishShip.png"))); // NOI18N
        jPanel2.add(Position4);
        Position4.setBounds(610, 240, 150, 110);

        Ocean1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OceanPosition.gif"))); // NOI18N
        jPanel2.add(Ocean1);
        Ocean1.setBounds(10, 80, 760, 290);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Original Position");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(310, 10, 130, 30);

        jLabel3.setText("Drag the ship below into the empty boxes to reposition the ship");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(230, 50, 310, 14);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Change The Position of Ship");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Position.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Position.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Position.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Position.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Position().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NewPosition0;
    private javax.swing.JLabel NewPosition1;
    private javax.swing.JLabel NewPosition2;
    private javax.swing.JLabel NewPosition3;
    private javax.swing.JLabel NewPosition4;
    private javax.swing.JLabel Ocean1;
    private javax.swing.JLabel Ocean2;
    private javax.swing.JLabel Position0;
    private javax.swing.JLabel Position1;
    private javax.swing.JLabel Position2;
    private javax.swing.JLabel Position3;
    private javax.swing.JLabel Position4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
