/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Faiz Ikhwann
 */
public class Qna extends javax.swing.JFrame {

    public String[] Ship={"French Ship","Greek Ship","Brazilian Ship","English Ship","Spanish Ship"};
    public double[] Arrive={5.00,6.00,8.00,9.00,7.00};
    public String[] Content={"Tea","Coffee","Cocoa","Rice","Corn"};
    public String[] Chimney={"Blue","Red","Black","White","Green"};
    public String[] Destination={"Genoa","Hamburg","Manila","Marseille","Port Said"};
    
    int i;
    
    
    public Qna() {
        initComponents();
        panelQna.setVisible(false);
        
    }
    
    public void Process(){
        ShipName.setText(Ship[i]);
        ShipName1.setText(Ship[i]);
        ShipName2.setText(Ship[i]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelQna = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        InfoLabel = new javax.swing.JLabel();
        ContentButton = new javax.swing.JRadioButton();
        ShipButton = new javax.swing.JRadioButton();
        RightButton = new javax.swing.JRadioButton();
        LeftButton = new javax.swing.JRadioButton();
        Content1Button = new javax.swing.JRadioButton();
        ShipName = new javax.swing.JLabel();
        ShipName1 = new javax.swing.JLabel();
        ShipName2 = new javax.swing.JLabel();
        ShipName4 = new javax.swing.JLabel();
        ButtonFrench = new javax.swing.JRadioButton();
        ButtonGreek = new javax.swing.JRadioButton();
        ButtonBrazilian = new javax.swing.JRadioButton();
        ButtonEnglish = new javax.swing.JRadioButton();
        ButtonSpanish = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelQNA = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuSoundOption = new javax.swing.JMenu();
        menuSoundOn = new javax.swing.JMenuItem();
        menuSoundOff = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));
        setPreferredSize(new java.awt.Dimension(470, 561));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(InfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(InfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ContentButton.setText("Content of the");
        ContentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContentButtonActionPerformed(evt);
            }
        });

        ShipButton.setText("The name of the ship");

        RightButton.setText("To the right of ");

        LeftButton.setText("To the left of");

        Content1Button.setText("Content of");

        javax.swing.GroupLayout panelQnaLayout = new javax.swing.GroupLayout(panelQna);
        panelQna.setLayout(panelQnaLayout);
        panelQnaLayout.setHorizontalGroup(
            panelQnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQnaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelQnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShipButton)
                    .addGroup(panelQnaLayout.createSequentialGroup()
                        .addComponent(ContentButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ShipName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelQnaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelQnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelQnaLayout.createSequentialGroup()
                                .addComponent(LeftButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ShipName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelQnaLayout.createSequentialGroup()
                                .addComponent(RightButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ShipName1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelQnaLayout.createSequentialGroup()
                                .addComponent(Content1Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ShipName4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelQnaLayout.setVerticalGroup(
            panelQnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelQnaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelQnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelQnaLayout.createSequentialGroup()
                        .addGroup(panelQnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ContentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShipName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(ShipButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RightButton))
                    .addComponent(ShipName1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelQnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LeftButton)
                    .addComponent(ShipName2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelQnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Content1Button)
                    .addComponent(ShipName4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ButtonFrench.setText("French Ship");
        ButtonFrench.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFrenchActionPerformed(evt);
            }
        });

        ButtonGreek.setText("Greek Ship");
        ButtonGreek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGreekActionPerformed(evt);
            }
        });

        ButtonBrazilian.setText("Brazilian Ship");
        ButtonBrazilian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBrazilianActionPerformed(evt);
            }
        });

        ButtonEnglish.setText("English Ship");
        ButtonEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnglishActionPerformed(evt);
            }
        });

        ButtonSpanish.setText("Spanish Ship");
        ButtonSpanish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSpanishActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Select a ship.");

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(348, 66));

        labelQNA.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelQNA.setText("Ship Information");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(labelQNA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelQNA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        jMenu1.setText("File");

        menuExit.setText("Exit");
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Option");

        menuSoundOption.setText("Sound");

        menuSoundOn.setText("Sound On");
        menuSoundOption.add(menuSoundOn);

        menuSoundOff.setText("Sound Off");
        menuSoundOption.add(menuSoundOff);

        jMenu2.add(menuSoundOption);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonFrench)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonGreek)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonBrazilian)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonEnglish)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonSpanish))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(panelQna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonFrench)
                    .addComponent(ButtonGreek)
                    .addComponent(ButtonBrazilian)
                    .addComponent(ButtonEnglish)
                    .addComponent(ButtonSpanish))
                .addGap(26, 26, 26)
                .addComponent(panelQna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonFrenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFrenchActionPerformed
        panelQna.setVisible(true);
        ButtonGreek.setSelected(false);
        ButtonEnglish.setSelected(false);
        ButtonBrazilian.setSelected(false);
        ButtonSpanish.setSelected(false);
        ButtonFrench.setSelected(true);
        i=0;
        Process();
    }//GEN-LAST:event_ButtonFrenchActionPerformed

    private void ButtonGreekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGreekActionPerformed
        panelQna.setVisible(true);
        ButtonGreek.setSelected(true);
        ButtonEnglish.setSelected(false);
        ButtonBrazilian.setSelected(false);
        ButtonSpanish.setSelected(false);
        ButtonFrench.setSelected(false);
        i=1;
        Process();
    }//GEN-LAST:event_ButtonGreekActionPerformed

    private void ButtonBrazilianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBrazilianActionPerformed
        panelQna.setVisible(true);
        ButtonGreek.setSelected(false);
        ButtonEnglish.setSelected(false);
        ButtonBrazilian.setSelected(true);
        ButtonSpanish.setSelected(false);
        ButtonFrench.setSelected(false);
        i=2;
        Process();
    }//GEN-LAST:event_ButtonBrazilianActionPerformed

    private void ButtonEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEnglishActionPerformed
        panelQna.setVisible(true);
        ButtonGreek.setSelected(false);
        ButtonEnglish.setSelected(true);
        ButtonBrazilian.setSelected(false);
        ButtonSpanish.setSelected(false);
        ButtonFrench.setSelected(false);
        i=3;
        Process();
    }//GEN-LAST:event_ButtonEnglishActionPerformed

    private void ButtonSpanishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSpanishActionPerformed
        panelQna.setVisible(true);
        ButtonGreek.setSelected(false);
        ButtonEnglish.setSelected(false);
        ButtonBrazilian.setSelected(false);
        ButtonSpanish.setSelected(true);
        ButtonFrench.setSelected(false);
        i=4;
        Process();
    }//GEN-LAST:event_ButtonSpanishActionPerformed

    private void ContentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContentButtonActionPerformed
        InfoLabel.setText("Ship's Name: "+Ship[i]+" "+Chimney[i]+" Chimney\n Content of the Ship: "+Content[i]+
                          "\nDestination: "+Destination[i]+"\nTime of Arrival: "+Arrive[i]+
                          " ");
    }//GEN-LAST:event_ContentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ButtonBrazilian;
    private javax.swing.JRadioButton ButtonEnglish;
    private javax.swing.JRadioButton ButtonFrench;
    private javax.swing.JRadioButton ButtonGreek;
    private javax.swing.JRadioButton ButtonSpanish;
    private javax.swing.JRadioButton Content1Button;
    private javax.swing.JRadioButton ContentButton;
    private javax.swing.JLabel InfoLabel;
    private javax.swing.JRadioButton LeftButton;
    private javax.swing.JRadioButton RightButton;
    private javax.swing.JRadioButton ShipButton;
    private javax.swing.JLabel ShipName;
    private javax.swing.JLabel ShipName1;
    private javax.swing.JLabel ShipName2;
    private javax.swing.JLabel ShipName4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelQNA;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuSoundOff;
    private javax.swing.JMenuItem menuSoundOn;
    private javax.swing.JMenu menuSoundOption;
    private javax.swing.JPanel panelQna;
    // End of variables declaration//GEN-END:variables
}
