import java.util.Formatter;
import java.util.Locale;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Faiz Ikhwan
 */
public class Table extends javax.swing.JFrame {

    /**
     * Creates new form Table
     */
    private Position pr = new Position();
    private Data[] q = new Data[5];
    private static int j = 0;
    StringBuilder sb = new StringBuilder();
    Formatter formatter = new Formatter(sb, Locale.US);
    private String[] temp = new String[5];
    
    public Table() {
        initComponents();
        setInfo();
        showTable();
    }

    public Table(int k) {
        initComponents();
        j = k;
        setInfo();
        showTable();
    }

    public void setInfo() {
        for (int l = 0; l < q.length; l++) {
            if (j == 0) {
                q[l] = pr.d[l];
            } else if (j == 1) {
                q[l] = pr.p[l];
            }
        }
    }
// https://docs.oracle.com/javase/1.5.0/docs/api/java/util/Formatter.html
// https://stackoverflow.com/questions/6000810/printing-with-t-tabs-does-not-result-in-aligned-columns
    public void showTable() {

        for(int i = 0; i<temp.length; i++)
        {
            temp[i] = String.format("%-9s %9s", q[i].Ship, q[i].Destination);
        }
            row1.setText(temp[0]);
            row2.setText(temp[1]);
            row3.setText(temp[2]);
            row4.setText(temp[3]);
            row5.setText(temp[4]);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        row1 = new javax.swing.JLabel();
        row2 = new javax.swing.JLabel();
        row3 = new javax.swing.JLabel();
        row4 = new javax.swing.JLabel();
        row5 = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();
        labelTable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainMenu.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 190, 40, 40);

        jButton2.setText("Show me the ship");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(130, 190, 140, 30);

        row1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        row1.setText("row1");
        jPanel1.add(row1);
        row1.setBounds(50, 30, 300, 15);

        row2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        row2.setText("row2");
        jPanel1.add(row2);
        row2.setBounds(50, 60, 300, 15);

        row3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        row3.setText("row3");
        jPanel1.add(row3);
        row3.setBounds(50, 90, 300, 15);

        row4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        row4.setText("row4");
        jPanel1.add(row4);
        row4.setBounds(50, 120, 300, 15);

        row5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        row5.setText("row5");
        jPanel1.add(row5);
        row5.setBounds(50, 150, 300, 15);

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OceanPosition.gif"))); // NOI18N
        jPanel1.add(backgroundImage);
        backgroundImage.setBounds(0, 0, 400, 240);

        labelTable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTable.setText("Table");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(labelTable)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTable, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new GraphicalShip().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelTable;
    private javax.swing.JLabel row1;
    private javax.swing.JLabel row2;
    private javax.swing.JLabel row3;
    private javax.swing.JLabel row4;
    private javax.swing.JLabel row5;
    // End of variables declaration//GEN-END:variables
}
